#######################
# Aurea Central Jervis Example
#######################
# User guide and documentation can be found at: https://github.com/trilogy-group/aurea-central-jervis-example
# This project is based on https://github.com/aurea-central-jervis-example/aurea-central-jervis

language: shell
jervis_version: feature/CFOT-303
variables:
  - CENTRAL_JERVIS_BRANCH=CFOT-626

branches:
  only:
    - /^qa.*$/

script:
  - echo 'Trying regression script'
  - touch 'test.txt'

services:
  ui-tests:
    regression-test:
      - name: RC Build Automated Tests. This test will run for ~3h, please be patient..
        raw: echo 'ok'
      - name: RC Build Automated Tests output
        raw: echo 'RC tests running..'

#trigger_cron_branch:
#  - develop
#trigger_cron_expression: 'H/2 * * * *'

jenkins:
  additional_labels: aes-edi-java-rocker
  stash:
    name: 'artifacts'
    allowEmpty: true
  collect:
    artifacts: 'test.txt'
  pipeline_jenkinsfile: aurea-central-jervis/pipelines/SaaS