#######################
# Aurea Central Jervis Example
#######################
# User guide and documentation can be found at: https://github.com/trilogy-group/aurea-central-jervis-example
# This project is based on https://github.com/aurea-central-jervis-example/aurea-central-jervis

language: shell

branches:
  only:
    - master
    - release
    - feature

#docker-agents:
#  - docker-image: registry2.swarm.devfactory.com/aurea/teamcity-linux/aes-edi:aesedi-8483-java8-maven-security
#    labels: language:shell aes-java

#trigger_cron_branch:
#  - develop
#  - release
#trigger_cron_expression: 'H/2 * * * *'

script:
  - echo 'Trying dev script'

jenkins:
  secrets:
    SECRET1: SECRET1
    SECRET2: SECRET2
  pipeline_jenkinsfile: custom-jenkins-file
