#######################
# Aurea Central Jervis Example
#######################
# User guide and documentation can be found at: https://github.com/trilogy-group/aurea-central-jervis-example
# This project is based on https://github.com/aurea-central-jervis-example/aurea-central-jervis

language: shell

variables:
  - BUILD_DOCKER_IMAGE_LABEL='stable && docker && ubuntu1604 && sudo && language-shell && env && aes-edi-java-rocker'

branches:
  only:
    - /^qa.*$/

docker-k8s-agents:
  - template-name: aes-edi
    docker-image: registry2.swarm.devfactory.com/aurea/teamcity-linux/aes-edi-java8-maven-security-rocker:latest
    labels: aes-edi-java-rocker
    remote-home-dir: /root

#trigger_cron_branch:
#  - develop
#  - release
#trigger_cron_expression: 'H/2 * * * *'

script:
  - touch test.txt

jenkins:
  additional_labels: aes-edi-java-rocker
  stash:
      name: 'artifacts'
      allowEmpty: true
    collect:
      artifacts: 'test.txt'
  pipeline_jenkinsfile: aurea-central-jervis/pipelines/SaaS

services:
  test-service:
    integration-test:
      - name: "Simulating {{ step_name }}"
        debug: msg="Hello world from {{ step_name }}"


notifications:
  email:
    recipients:
      - to: anuj.gupta@aurea.com
        on_success: always
        on_failure: always
