#######################
# Aurea Central Jervis Example
#######################
# User guide and documentation can be found at: https://github.com/trilogy-group/aurea-central-jervis-example
# This project is based on https://github.com/aurea-central-jervis-example/aurea-central-jervis

language: shell

jervis_version: separate-stages

branches:
  only:
    - master
    - qa/1.0.0
    - feature

#docker-agents:
#  - docker-image: registry2.swarm.devfactory.com/aurea/teamcity-linux/aes-edi:aesedi-8483-java8-maven-security
#    labels: aes-java

#trigger_cron_branch:
#  - develop
#  - release
#trigger_cron_expression: 'H/2 * * * *'

#docker-k8s-agents:
#  - template-name: aes-edi
#    docker-image: registry2.swarm.devfactory.com/aurea/teamcity-linux/aes-edi-java8-maven-security-rocker:latest
#    labels: aes-edi-java-rocker
#    remote-home-dir: /root

before_install:
  - echo 'In before install section'

install:
  - echo 'In install section'

before_script:
  - echo 'In before script section'

script:
  - echo 'Trying dev script'
  - echo "Before"
  - if [ ! -z "$SECRET1" ]; then echo "Got correct secret!"; fi
  - echo "After"

jenkins:
  secrets:
    SECRET1: MY_SECRET_1
    SECRET2: SECRET2
